-- ═══════════════════════════════════════════════════
-- DeineStimme.org — Einladungscodes
-- Nach dem Hauptschema ausführen
-- ═══════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS invite_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  scope TEXT NOT NULL DEFAULT 'plattform',
  used BOOLEAN DEFAULT false,
  used_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  used_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Codes prüfbar" ON invite_codes FOR SELECT USING (true);
CREATE POLICY "Codes einlösbar" ON invite_codes FOR UPDATE USING (true);

INSERT INTO invite_codes (code, scope) VALUES
  ('MOND-ALPHA-2026', 'plattform'),
  ('MOND-BETA-2026', 'plattform'),
  ('MOND-GAMMA-2026', 'plattform'),
  ('MOND-DELTA-2026', 'plattform'),
  ('MOND-EPSILON-2026', 'plattform'),
  ('KOMPASS-ALPHA-2026', 'schreibkompass'),
  ('KOMPASS-BETA-2026', 'schreibkompass'),
  ('KOMPASS-GAMMA-2026', 'schreibkompass'),
  ('KOMPASS-FAUST-2026', 'schreibkompass'),
  ('KOMPASS-HAMLET-2026', 'schreibkompass'),
  ('KOMPASS-SHERLOCK-2026', 'schreibkompass'),
  ('KOMPASS-GATSBY-2026', 'schreibkompass'),
  ('KOMPASS-ATTICUS-2026', 'schreibkompass'),
  ('KOMPASS-FRODO-2026', 'schreibkompass'),
  ('KOMPASS-HERMIONE-2026', 'schreibkompass'),
  ('KOMPASS-KATNISS-2026', 'schreibkompass'),
  ('KOMPASS-ALICE-2026', 'schreibkompass'),
  ('KOMPASS-BILBO-2026', 'schreibkompass'),
  ('KOMPASS-ORWELL-2026', 'schreibkompass'),
  ('KOMPASS-KAFKA-2026', 'schreibkompass'),
  ('KOMPASS-TOLKIEN-2026', 'schreibkompass'),
  ('KOMPASS-ROWLING-2026', 'schreibkompass'),
  ('KOMPASS-HEMINGWAY-2026', 'schreibkompass'),
  ('KOMPASS-AUSTEN-2026', 'schreibkompass'),
  ('KOMPASS-DICKENS-2026', 'schreibkompass'),
  ('KOMPASS-POE-2026', 'schreibkompass'),
  ('KOMPASS-GOETHE-2026', 'schreibkompass'),
  ('KOMPASS-TWAIN-2026', 'schreibkompass'),
  ('VERTRAG-ALPHA-2026', 'vertragsanalyse'),
  ('VERTRAG-BETA-2026', 'vertragsanalyse'),
  ('VERTRAG-GAMMA-2026', 'vertragsanalyse'),
  ('VERTRAG-SPECTER-2026', 'vertragsanalyse'),
  ('VERTRAG-ROSS-2026', 'vertragsanalyse'),
  ('VERTRAG-GOODMAN-2026', 'vertragsanalyse'),
  ('VERTRAG-KEATING-2026', 'vertragsanalyse'),
  ('VERTRAG-LOCKHART-2026', 'vertragsanalyse'),
  ('VERTRAG-SHORE-2026', 'vertragsanalyse'),
  ('VERTRAG-CRANE-2026', 'vertragsanalyse'),
  ('VERTRAG-WEXLER-2026', 'vertragsanalyse'),
  ('VERTRAG-FLORRICK-2026', 'vertragsanalyse'),
  ('VERTRAG-GINSBURG-2026', 'vertragsanalyse'),
  ('VERTRAG-SOTOMAYOR-2026', 'vertragsanalyse'),
  ('VERTRAG-ROBERTS-2026', 'vertragsanalyse'),
  ('VERTRAG-THOMAS-2026', 'vertragsanalyse'),
  ('VERTRAG-ALITO-2026', 'vertragsanalyse'),
  ('VERTRAG-KAGAN-2026', 'vertragsanalyse'),
  ('VERTRAG-GORSUCH-2026', 'vertragsanalyse'),
  ('VERTRAG-KAVANAUGH-2026', 'vertragsanalyse'),
  ('VERTRAG-BARRETT-2026', 'vertragsanalyse'),
  ('VERTRAG-JACKSON-2026', 'vertragsanalyse'),
  ('VERTRAG-SCALIA-2026', 'vertragsanalyse'),
  ('GERO-ADMIN-2026', 'alles'),
  ('TESTER-VIP-2026', 'alles'),
  ('HASE-HOPPEL-2026', 'plattform'),
  ('HASE-SCHNUFFEL-2026', 'plattform'),
  ('HASE-MUCKI-2026', 'plattform'),
  ('HASE-BOBBY-2026', 'plattform'),
  ('HASE-PAULI-2026', 'plattform'),
  ('HASE-FELIX-2026', 'plattform'),
  ('HASE-BRUNO-2026', 'plattform'),
  ('HASE-THEO-2026', 'plattform'),
  ('HASE-LUNA-2026', 'plattform'),
  ('HASE-BELLA-2026', 'plattform'),
  ('HASE-NALA-2026', 'plattform'),
  ('HASE-MINKA-2026', 'plattform'),
  ('HASE-LILLY-2026', 'plattform'),
  ('HASE-EMMA-2026', 'plattform'),
  ('HASE-SOPHIE-2026', 'plattform'),
  ('HASE-MIA-2026', 'plattform'),
  ('HASE-FLÖCKCHEN-2026', 'plattform'),
  ('HASE-WOLKE-2026', 'plattform'),
  ('HASE-MÖHRE-2026', 'plattform'),
  ('HASE-PÜPPI-2026', 'plattform'),
  ('HASE-KNUDDEL-2026', 'plattform'),
  ('HASE-ZOTTEL-2026', 'plattform'),
  ('HASE-KAROTTE-2026', 'plattform'),
  ('HASE-SALAT-2026', 'plattform'),
  ('HASE-TURBO-2026', 'plattform'),
  ('HASE-BLITZ-2026', 'plattform'),
  ('HASE-WUSCHEL-2026', 'plattform'),
  ('HASE-QUIRL-2026', 'plattform'),
  ('HASE-RABAUK-2026', 'plattform'),
  ('HASE-ZAPPEL-2026', 'plattform'),
  ('HASE-HOPSI-2026', 'plattform'),
  ('HASE-FLITZI-2026', 'plattform'),
  ('HASE-LANGOHR-2026', 'plattform'),
  ('HASE-GRAUFELL-2026', 'plattform'),
  ('HASE-SCHNEFLOCKE-2026', 'plattform'),
  ('HASE-SCHOKOHASE-2026', 'plattform'),
  ('HASE-KAKAOBÖHNCHEN-2026', 'plattform'),
  ('HASE-ZIMSTERNE-2026', 'plattform'),
  ('HASE-PFEFFER-2026', 'plattform'),
  ('HASE-MUSKAT-2026', 'plattform'),
  ('HASE-HASELNUSS-2026', 'plattform'),
  ('HASE-KAKAO-2026', 'plattform'),
  ('HASE-NUGAT-2026', 'plattform'),
  ('HASE-MARSHMALLOW-2026', 'plattform'),
  ('HASE-KOKOS-2026', 'plattform'),
  ('HASE-SAHNE-2026', 'plattform'),
  ('HASE-LOKI-2026', 'plattform'),
  ('HASE-MILA-2026', 'plattform'),
  ('HASE-FINN-2026', 'plattform'),
  ('HASE-LOTTA-2026', 'plattform'),
  ('HASE-OSKAR-2026', 'plattform'),
  ('HASE-FRIDA-2026', 'plattform'),
  ('HASE-LEO-2026', 'plattform'),
  ('HASE-GRETA-2026', 'plattform');
